### ISSUE TITLE
Error Code

### ISSUE THREAD

**Issue by Whamp** [yracine/customYaleLockWithGoodTimeout#1]
Groovy.lang.MissingMethodException: No signature of method: script1422908499390514913223.page() is applicable for argument types: (java.util.LinkedHashMap) values: [[name:controllerSetup]] Possible solutions: path(java.lang.Object), wait(), any(), wait(long), main(java.lang.String), main(java.util.List)

**Comment by Whamp** [comment]
I received the above error when using this code when trying to add a new device type to handle a MonoPrice Deadbolt Z-wave lock. Any ideas on the issue here ?

**Comment by yracine** [comment]
No idea, I cannot reproduce your error.
